version: '3'
services:
  artemis-live:
    image: vromero/activemq-artemis:2.4.0
    ports:
      - "8161:8161"
      - "61617:61617"
      - "1199:1199"
      - "1198:1198"
    environment:
      ARTEMIS_USERNAME: admin
      ARTEMIS_PASSWORD: admin
      ARTEMIS_MIN_MEMORY: 256M
      ARTEMIS_MAX_MEMORY: 1024M
      ARTEMIS_PERF_JOURNAL: AUTO
      ENABLE_JMX: 'true'
      JMX_PORT: 1199
      JMX_RMI_PORT: 1198
      JAVA_TOOL_OPTIONS: "-Dlive.host=artemis-live -Dlive.port=61617 -Dbackup.host=artemis-backup -Dbackup.port=61626"
    volumes:
      - ./broker1:/var/lib/artemis/etc-override
      #- ./broker1/etc:/var/lib/artemis/etc

  artemis-backup:
    image: vromero/activemq-artemis:2.4.0
    ports:
      - "8171:8161"
      - "61626:61626"
      - "1209:1209"
      - "1208:1209"
    environment:
      ARTEMIS_USERNAME: admin
      ARTEMIS_PASSWORD: admin
      ARTEMIS_MIN_MEMORY: 256M
      ARTEMIS_MAX_MEMORY: 1024M
      ARTEMIS_PERF_JOURNAL: AUTO
      ENABLE_JMX: 'true'
      JMX_PORT: 1209
      JMX_RMI_PORT: 1209
      JAVA_TOOL_OPTIONS: "-Dlive.host=artemis-live -Dlive.port=61617 -Dbackup.host=artemis-backup -Dbackup.port=61626"
    volumes:
      #- ./broker2:/var/lib/artemis/etc-override
      - ./broker2/etc:/var/lib/artemis/etc

volumes:
  data:
